name: sunmi_aidl_print_example
description: Demonstrates how to use the sunmi_aidl_print plugin.
publish_to: 'none'

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  qr_flutter: ^2.1.0
  flutter_bloc: ^0.21.0
  equatable: ^0.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  sunmi_aidl_print:
    path: ../

flutter:
  uses-material-design: true

  fonts:
    - family: Sansita
      fonts: 
        - asset: assets/fonts/Sansita-Regular.ttf
    - family: Pantone
      fonts:
        - asset: assets/fonts/Panton-Regular.ttf
